export const services = [
  { slug: 'engine-swaps', name: 'Engine & transmission swaps', short: 'Engine swaps', display: 'A new heart.\nThe same attitude.', description: 'Engine, transmission and custom motor swaps in Tampa. Talk through your vehicle and build goals with Flock Built Performance.', intro: 'Motor swaps. Transmission swaps. Custom combinations. Bring us your vehicle and your plan, and we’ll talk through the next step.', items: ['Engine swaps', 'Transmission swaps', 'Custom motor swaps'], faq: [['Can you quote a swap from photos?', 'Photos and the year, make and model help start the conversation. The shop will confirm the parts and work after reviewing your vehicle.'], ['Should I buy parts first?', 'Talk with the shop before buying parts so the proposed combination can be reviewed.'], ['Do you have a build I can see?', 'The red Civic EG is in the build showcase. Its detailed parts list is waiting for the owner’s approved story.']] },
  { slug: 'diesel', name: 'Diesel repair', short: 'Diesel repair', display: 'Keep the workhorse\nworking.', description: 'Diesel repair in Tampa from Flock Built Performance. Describe your truck, symptoms and repair needs to start an estimate.', intro: 'A truck that works needs a shop that gets straight to the problem. Tell us what you drive and what it’s doing.', items: ['Diesel repair', 'Starting and charging concerns', 'Repair assessment'], faq: [['What information should I send?', 'Send the year, make, model, engine if known, and the symptoms. A photo or short description helps the shop review your request.'], ['Can you tow my truck?', '24-hour towing is offered. Call to confirm the vehicle, pickup location and equipment availability.'], ['Do you service my engine?', 'Call or send an estimate request with your engine details. Specific engine coverage is confirmed by the shop.']] },
  { slug: 'check-engine-light', name: 'Check-engine diagnostics', short: 'Diagnostics', display: 'Light on?\nLet’s find out why.', description: 'Check-engine-light diagnostics in Tampa. Contact Flock Built Performance with symptoms, warning lights and your vehicle details.', intro: 'A warning light is a place to start. Tell us what changed, when it happened and what you’re noticing behind the wheel.', items: ['Check-engine light', 'Starting concerns', 'Running concerns'], faq: [['Is diagnosis included in a free estimate?', 'Estimates are free. Any separate diagnostic fee needs to be confirmed with the shop before work begins.'], ['Can I drive with the light on?', 'Call with your symptoms before bringing the vehicle in. If you are unsure the vehicle is safe to drive, ask about towing.'], ['What should I include?', 'Your vehicle details, symptoms, any code you already have, and a dashboard photo if available.']] },
  { slug: 'brakes', name: 'Brake repair', short: 'Brakes', display: 'Confidence at\nevery stop.', description: 'Brake repair in Tampa from Flock Built Performance. Request an estimate for brake concerns with your vehicle details.', intro: 'Noise, vibration or a change in pedal feel? Describe the concern and get the next step from the shop.', items: ['Brake repair', 'Brake concerns', 'Vehicle assessment'], faq: [['What does a brake job cost?', 'The shop confirms current pricing, parts and what is included after reviewing the vehicle. Historical flyer specials are not current offers.'], ['Can I bring the vehicle straight in?', 'Appointments are recommended. Call ahead for gate access and to agree on an arrival time.'], ['What if the vehicle cannot be driven?', 'Ask about towing when you call, with the pickup and drop-off locations ready.']] },
  { slug: 'oil-change-tune-up', name: 'Oil changes & tune-ups', short: 'Oil & tune-ups', display: 'The basics.\nDone right.', description: 'Oil changes and tune-ups in Tampa. Contact Flock Built Performance to confirm service details and current prices.', intro: 'Keep up with the work your vehicle needs. Tell us the year, make and model, and ask what’s included before booking.', items: ['Oil changes', 'Tune-ups', 'Routine service enquiries'], faq: [['Can I bring my own oil?', 'A bring-your-own-oil offer appeared in a May 2026 flyer. Ask the shop whether it is still available and what oil and filter are required.'], ['What is included in a tune-up?', 'The scope depends on your vehicle. The shop will confirm the parts and work included in your estimate.'], ['How do I book?', 'Call, text or request an estimate, then agree on a time and gate instructions.']] },
];
export const transportServices = ['tow', 'vehicle-transport', 'equipment-transport', 'hotshot'];
export const quoteChoices = [
  ['repair', 'Auto / diesel repair'], ['engine-swaps', 'Engine / transmission swap'],
  ['check-engine-light', 'Diagnostics'], ['brakes', 'Brakes'], ['oil-change-tune-up', 'Oil change / tune-up'],
  ['tow', 'Tow'], ['vehicle-transport', 'Vehicle transport'], ['equipment-transport', 'Equipment transport'],
  ['hotshot', 'Hotshot delivery'], ['other', 'Other'],
];
